name: Topic Testing

on:
  workflow_dispatch:

jobs:
  run_script:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      # checks out the repo content to GitHub runner
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8.1" # install python version needed
      - name: install python packages
        run: |
          python -m pip install --upgrade pip --user
          python -m pip install pandas --user
          python -m pip install requests --user
      - name: Git Config User
        run: |
          git config --global user.email "lopezjoa@iu.edu"
          git config --global user.name "lopezjoa"
#       - name: Getting Github Cloud Data OLD
#         env:
#           JL_PAT: ${{ secrets.JL_PAT}}
#         run: |
#           git status
#           python import_cloud_old.py
#           git add .
#           git commit -m "Got list of repos"
#           git push
      - name: Running Topic Script
        env:
          JL_PAT: ${{ secrets.JL_PAT}}
        run: |
          git status
          python add_topics.py [myRepo, aaa, bbb] [otherRepo, ccc] [anotherRepo, ddd] [ , frg ]
          git add .
          git commit -m "Topics added"
          git push

